server:
    port: 8763
spring:
    application:
        name: service-helloworld
    cloud:
        config:
          label: master
          profile: dev
#          uri: http://localhost:8761/eureka/
          discovery:
                   enabled: true
                   serviceId: config-server